#### CPAL color hex groups #####
hex_ten = c("#008097", #teal
            "#E98816", #orange
            "#595959", #dark grey
            "#EA8B98", #light pink
            "#EACA2D", #bumblebee

            "#851E2C", #antique ruby
            "#1E4A4A", #dark slate green
            "#F7314C", #sizzling red
            "#07F2D3", #sea green crayola
            "#6996C9" #blue gray
)

hex_fiv = c("#008097", #teal
             "#E98816", #orange
             "#595959", #dark grey
             "#EA8B98", #light pink
             "#EACA2D" #bumblebee
)

hex_tri = c("#008097", #teal
              "#E98816", #orange
              "#59074D" #purple
)

hex_div = c("#008097", #teal
            "#E7ECEE", #white
            "#E98816" #orange
)

hex_two = c("#008097", #teal
            "#E98816" #orange
)

#### CPAL color rgb groups #####
r_ten <- col2rgb(hex_ten)[1, ]
g_ten <- col2rgb(hex_ten)[2, ]
b_ten <- col2rgb(hex_ten)[3, ]

r_fiv <- col2rgb(hex_fiv)[1, ]
g_fiv <- col2rgb(hex_fiv)[2, ]
b_fiv <- col2rgb(hex_fiv)[3, ]

r_tri <- col2rgb(hex_tri)[1, ]
g_tri <- col2rgb(hex_tri)[2, ]
b_tri <- col2rgb(hex_tri)[3, ]

r_div <- col2rgb(hex_div)[1, ]
g_div <- col2rgb(hex_div)[2, ]
b_div <- col2rgb(hex_div)[3, ]

r_two <- col2rgb(hex_two)[1, ]
g_two <- col2rgb(hex_two)[2, ]
b_two <- col2rgb(hex_two)[3, ]

#### CPAL color palette function #####
#' Generates a color palette based on CPAL standards
#'
#' @param n total number of hex values to be generated by palette
#' @param name name of color palette to generate hex values from
#'
#' @return A dataframe with a list n hex values for the chosen color palette
#' @export
#'
#' @examples
#' div_OrTe <- cpal_palette(n = 30, name = "cpal_div")
#' par(mar = rep(0, 4))
#' pie(rep(1, length(div_OrTe)), col = div_OrTe)
#' @import grDevices
cpal_palette <- function (n, name = c("cpal_ten", "cpal_fiv", "cpal_tri", "cpal_div", "cpal_two"))
{
  cpal_ten = rgb(r_ten,g_ten,b_ten,maxColorValue = 255)
  cpal_fiv = rgb(r_fiv,g_fiv,b_fiv,maxColorValue = 255)
  cpal_tri = rgb(r_tri,g_tri,b_tri,maxColorValue = 255)
  cpal_div = rgb(r_div,g_div,b_div,maxColorValue = 255)
  cpal_two = rgb(r_two,g_two,b_two,maxColorValue = 255)

  name = match.arg(name)
  orig = eval(parse(text = name))
  rgb = t(col2rgb(orig))
  temp = matrix(NA, ncol = 3, nrow = n)
  x = seq(0, 1, , length(orig))
  xg = seq(0, 1, , n)
  for (k in 1:3) {
    hold = spline(x, rgb[, k], n = n)$y
    hold[hold < 0] = 0
    hold[hold > 255] = 255
    temp[, k] = round(hold)
  }
  palette = rgb(temp[, 1], temp[, 2], temp[, 3], maxColorValue = 255)
  palette
}
